src/IdentityPoc/Poc.Identity.MvcClient/Controllers/HomeController.cs
namespace Poc.Identity.MvcClient.Controllers
{
    using System.Web.Mvc;

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/IdentityPoc/Poc.Identity.MvcClient/Controllers/SecuredApiCallController.cs
namespace Poc.Identity.MvcClient.Controllers
{
    using System.Net.Http;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using Newtonsoft.Json.Linq;

    public class SecuredApiCallController : AsyncController
    {
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var accessToken = (User as ClaimsPrincipal).FindFirst("access_token").Value;

            var httpClient = new HttpClient();
            httpClient.SetBearerToken(accessToken);

            var jsonData = await httpClient.GetStringAsync("http://localhost:2762/claims");
            ViewBag.WebApiData = JArray.Parse(jsonData).ToString();

            return View();
        }
    }
}

src/IdentityPoc/Poc.Identity.MvcClient/Controllers/SecuredController.cs
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace Poc.Identity.MvcClient.Controllers
{
    public class SecuredController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            var calimedUser = User as ClaimsPrincipal;

            ViewBag.CurrentAuthData = calimedUser.Claims.Aggregate(string.Empty, (acc, c) => acc + " " + c.ToString());

            return View();
        }
    }
}

src/IdentityPoc/Poc.Identity.MvcClient/Controllers/SecuredForAdminController.cs
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;

namespace Poc.Identity.MvcClient.Controllers
{
    public class SecuredForAdminController : Controller
    {
        [Authorize]
        [ResourceAuthorize("Read", "SomeInfo")]
        [HandleForbidden]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/IdentityPoc/Poc.Identity.MvcClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Open Id test + claims</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/IdentityPoc/Poc.Identity.MvcClient/Views/Secured/Index.cshtml
@{
    ViewBag.Title = "Secured page";
}

<div class="jumbotron">
    <h1>Auth + claims</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Your claims</h2>
        <p>
            @ViewBag.CurrentAuthData
        </p>
    </div>

</div>

src/IdentityPoc/Poc.Identity.MvcClient/Views/SecuredApiCall/Index.cshtml
@{
    ViewBag.Title = "Secured page";
}

<div class="jumbotron">
    <h1>Auth + claims</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Claims info from web api:</h2>
        <p>
            @ViewBag.WebApiData
        </p>
    </div>

</div>

src/IdentityPoc/Poc.Identity.MvcClient/Views/SecuredForAdmin/Index.cshtml
@{
    ViewBag.Title = "Resource security";
}

<div class="jumbotron">
    <h1>Auth + claims</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <p>
            if you see this you are in admin role
        </p>
    </div>

</div>

src/IdentityPoc/Poc.Identity.MvcClient/Views/Shared/Forbidden.cshtml
@{
    ViewBag.Title = "Forbidden";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Forbidden</h2>

src/IdentityPoc/Poc.Identity.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("AuthOnly", "Index", "Secured")</li>
                    <li>@Html.ActionLink("AdminOnly", "Index", "SecuredForAdmin")</li>
                    <li>@Html.ActionLink("WebApiActaAs", "Index", "SecuredApiCall")</li>
                    @if (User.Identity.IsAuthenticated) {
                        <li>@Html.ActionLink("LOGOUT", "Logout", "SecuredForAdmin")</li>
                        }
                </ul>
            </div>
        </div>
      
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
            <div>
                @if (User.Identity.IsAuthenticated)
                {
                    @User.Identity.Name
                }
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>